setting:
  name: "test_ncd_128"
  output_root: "./experiments"
  # pc_path: "./data/ncd_128/math_easy/ply"
  # pose_path: "./data/ncd_128/math_easy/poses.txt" 
  # deskew: True

  # deskew_origin: False # *
  deskew: True # True *
  source_from_ros: True # *
  gpu_id: "1" # *
  begin_frame: 0

process:
  min_range_m: 1.5
  max_range_m: 60.0
  min_z_m: -10.0
  vox_down_m: 0.08
  adaptive_range_on: True

  estimate_normal: True # *
sampler:
  surface_sample_range_m: 0.35
  surface_sample_n: 4
  free_sample_begin_ratio: 0.5
  free_sample_end_dist_m: 1.2
  free_front_sample_n: 2 
neuralpoints:
  voxel_size_m: 0.4
  feature_dim: 8 
  query_nn_k: 6
  search_alpha: 0.5
  weighted_first: False
  # use_mid_ts: True

training:
  attention_mode: True # *
decoder:
  mlp_hidden_dim: 32 #64
  freeze_after_frame: 40 #40/50
  # mlp_checkpoint_path: "pretrained_mlp_checkpoints/pretrain_ncm_ncminemed/geo_mlp.pth"
  # mlp_checkpoint_path: "pretrained_mlp_checkpoints/pretrain_nce_ncm/geo_mlp.pth"
  mlp_checkpoint_path: "pretrained_mlp_checkpoints/pretrain_ncm_kitti360/geo_mlp.pth"

loss:
  main_loss_type: bce
  sigma_sigmoid_m: 0.1
  loss_weight_on: True
  dist_weight_scale: 0.8
  ekional_loss_on: True
  weight_e: 0.5
continual:
  batch_size_new_sample: 3000 # 1000
  pool_capacity: 2e7 # 1e7

tracker:
  source_vox_down_m: 0.6
  iter_n: 100

  lm_lambda: 5e-3 # *

imu_pgo: True # True *

# pgo:
#   map_context: True
#   pgo_freq_frame: 30
optimizer: # mapper
  iters: 15  # iterations per frame
  batch_size: 10000 #16384
  # ba_freq_frame: 20
eval:
  wandb_vis_on: True # log to wandb or not
  o3d_vis_on: False # visualize the mapping or not
  # mesh_freq_frame: 50 # reconstruct the mesh every x frames
  # mesh_min_nn: 15
  save_map: True